### ISSUE TITLE
Alpha 0.1.14 under Windows 10 64-bit：IRI exited with status 1

### ISSUE THREAD

**Issue by xq0404** [SemkoDev/bolero.fun#57] opened 2018-01-30 07:20 UTC
After installing Alpha 0.1.14 on Windows 10 64-bit, there appers a bummer with "IRI exited with status 1".
Alpha 0.1.14 works under Windows 7 64-bit, showing "IRI Synchonized? Yes(338000/338000)". But unfortuantely, the IOTA Light Wallet cannot make use of the local http://localhost:14265 created by bolerro.fun, displaying "not synced".

**Comment by stereu** [comment] 2018-01-30 07:55
#55 #45 Already exists! If there is not your solution provide your default.log

**Comment by xq0404** [comment] 2018-01-30 08:13
What about displaying "not synced"？

**Comment by romansemko** [comment] 2018-02-01 06:14
Duplicate of #45 , please use it for reference. A possible fix is coming today/tomorrow

**Closed as completed by romansemko** 2018-02-01 06:14 UTC
