### ISSUE TITLE
IRI seems down...

### ISSUE THREAD

**Issue by armstrys** [SemkoDev/bolero.fun#48] opened 2018-01-26 17:19 UTC
Keep getting this error. It just repeats and repeats. 

"Fri Jan 26 2018 11:19:18 GMT-0600 (CST) iri: starting...
Fri Jan 26 2018 11:19:18 GMT-0600 (CST) iri: IRI seems down, trying to restart in 5 seconds...
Fri Jan 26 2018 11:19:18 GMT-0600 (CST) iri: stopped"

Am I missing a step? The download and extraction went smoothly.

**Comment by armstrys** [comment] 2018-01-26 17:23
Sorry, let me add to this. I rebooted bolero and it seemed to be running but then went into this error loop above. Full log below. IRI exit code 255.

"Fri Jan 26 2018 11:22:00 GMT-0600 (CST) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12
Fri Jan 26 2018 11:22:00 GMT-0600 (CST) system: Java version line: [java version "1.8.0_161"]
Fri Jan 26 2018 11:22:00 GMT-0600 (CST) system: Java version detected: [1.8.0_161]
Fri Jan 26 2018 11:22:00 GMT-0600 (CST) iri: starting...
Fri Jan 26 2018 11:22:01 GMT-0600 (CST) nelson: started
Fri Jan 26 2018 11:22:01 GMT-0600 (CST) iri: STDOUT: 01/26 11:22:01.510 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.7

Fri Jan 26 2018 11:22:01 GMT-0600 (CST) iri: started
Fri Jan 26 2018 11:22:07 GMT-0600 (CST) iri: STDOUT: 01/26 11:22:07.668 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 

Fri Jan 26 2018 11:22:07 GMT-0600 (CST) iri: STDOUT: 01/26 11:22:07.742 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.

Fri Jan 26 2018 11:22:07 GMT-0600 (CST) iri: STDERR: 01/26 11:22:07.786 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation: 
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainDatagramSocketImpl.bind0(Native Method) ~[na:1.8.0_161]
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93) ~[na:1.8.0_161]
	at java.net.DatagramSocket.bind(DatagramSocket.java:392) ~[na:1.8.0_161]
	at java.net.DatagramSocket.<init>(DatagramSocket.java:242) ~[na:1.8.0_161]
	at java.net.DatagramSocket.<init>(DatagramSocket.java:299) ~[na:1.8.0_161]
	at java.net.DatagramSocket.<init>(DatagramSocket.java:271) ~[na:1.8.0_161]
	at com.iota.iri.network.UDPReceiver.init(UDPReceiver.java:49) ~[iri-1.4.1.7.jar:na]
	at com.iota.iri.Iota.init(Iota.java:109) ~[iri-1.4.1.7.jar:na]
	at com.iota.iri.IRI.main(IRI.java:73) ~[iri-1.4.1.7.jar:na]

Fri Jan 26 2018 11:22:07 GMT-0600 (CST) iri: STDOUT: 01/26 11:22:07.786 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...

Fri Jan 26 2018 11:22:14 GMT-0600 (CST) iri: STDERR: 01/26 11:22:14.510 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
	at com.iota.iri.network.replicator.ReplicatorSourcePool.shutdown(ReplicatorSourcePool.java:76) ~[iri-1.4.1.7.jar:na]
	at com.iota.iri.network.replicator.Replicator.shutdown(Replicator.java:30) ~[iri-1.4.1.7.jar:na]
	at com.iota.iri.Iota.shutdown(Iota.java:176) ~[iri-1.4.1.7.jar:na]
	at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:251) ~[iri-1.4.1.7.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]"

**Comment by romansemko** [comment] 2018-01-29 07:20
Seems a duplicate of #45

**Closed as completed by romansemko** 2018-01-29 07:20 UTC

**Comment by armstrys** [comment] 2018-01-29 13:46
Will check it out. Thanks!
