### ISSUE TITLE
Database deleted after restart

### ISSUE THREAD

**Issue by newSami** [SemkoDev/bolero.fun#56] opened 2018-01-29 20:30 UTC
When I restart bolero, database is deleted and has to be downloaded again. Is this normal?

**Comment by stereu** [comment] 2018-01-29 22:52
I think it's normal that the software shows an empty database for a certain time after startup. Just wait a few minutes for peers and the milestones will show up in GUI. I don't think that there were really wiped from the disk.

**Comment by newSami** [comment] 2018-01-30 10:29
When I turn off bolero, db folder is still there. But when I start bolero again, db folder is deleted and database is going to sync from the begining (338000).

**Comment by tiker** [comment] 2018-01-30 21:52
I've got the same issue here on Windows.  Stopped the node to move the database files to a dedicated disk and the DB was deleted when starting the node again.  In my case, I'm looking to see if I block this with denying delete permissions in NTFS but no luck so far.

Hopefully this is a bug and not something by design.

**Comment by romansemko** [comment] 2018-01-31 05:51
Hmm, can you check if there is a file called "settings.json" in your .bolero folder?

If yes, could you post it here?
Otherwise, try creating a new one with the following content:

`{"version":0,"databaseVersion":"1.4.2.1"}`

Let me know if it solves it!

**Comment by tiker** [comment] 2018-01-31 13:30
With my node, the file exists but contains the previous version:
`{"version":0,"databaseVersion":"1.4.1.7"}`

Edit:
I should probably add that I am using 1.4.2.1.
First two lines from current.log:
`Tue Jan 30 2018 17:31:59 GMT-0500 (Eastern Standard Time) system: Java: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Tue Jan 30 2018 17:31:59 GMT-0500 (Eastern Standard Time) system: Java version line: [java version "1.8.0_161"
]
Tue Jan 30 2018 17:31:59 GMT-0500 (Eastern Standard Time) system: Java version detected: [1.8.0_161
]
Tue Jan 30 2018 17:31:59 GMT-0500 (Eastern Standard Time) iri: starting...
Tue Jan 30 2018 17:32:00 GMT-0500 (Eastern Standard Time) iri: STDOUT: 01/30 17:32:00.545 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.1
`

I also down graded the version of RocksDB.something.dll in the 1.4.2.1 .jar file for this to run on Windows.

**Comment by OleWouters** [comment] 2018-01-31 16:10
Had the same issue, my settings.json said 1.4.1.7 after I changed it to 1.4.2.1 it's not deleting it anymore :)

**Comment by newSami** [comment] 2018-01-31 18:23
OK, changing to 1.4.2.1 solved the problem :+1:

**Comment by romansemko** [comment] 2018-02-01 06:22
Hmm, strange. After deleting the database for reset, it should have updated the setting to 1.4.2.1. I will investigate. Thanks for the input!

**Comment by romansemko** [comment] 2018-02-01 06:24
Found the bug for Windows users. Will be fixed in the next release. Thanks for your input, everyone!

**Closed as completed by romansemko** 2018-02-01 06:24 UTC
Labels: bug

**Comment by OleWouters** [comment] 2018-02-01 07:16
Nice!!

**Comment by romansemko** [comment] 2018-02-01 08:46
It's fixed. However, it will try to delete the database one last time, if you start the new version. To avoid this, you can manually change the database version as explained above before starting the new version! Afterwards it will behave nicely on restarts.

**Comment by tiker** [comment] 2018-02-01 17:31
Thanks for the fix!
