### ISSUE TITLE
error: java v1.8.0_151 or higher is not installed, but it is

### ISSUE THREAD

**Issue by boxcee** [SemkoDev/bolero.fun#41] opened 2018-01-15 13:23 UTC
Hey, how does bolero (or, I assume IRI) detect the Java version on linux?

`java -version`

`java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)`

Mine is correct, but bolero shows me `error: java v1.8.0_151 or higher is not installed`.

EDIT:
`echo $JAVA_HOME = /usr/lib/jvm/java-8-oracle/bin/java`

**Comment by Kwintspiracy** [comment] 2018-01-16 12:11
Same here!

**Comment by romansemko** [comment] 2018-01-25 10:55
Please try version 0.1.13. It will report java version feedback in the logs view in Bolero. If it still gives you problems, could you past the logs from the logs view? Thanks!

**Comment by boxcee** [comment] 2018-01-25 12:36
`Thu Jan 25 2018 13:35:30 GMT+0100 (CET) system: Java: 
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15
Thu Jan 25 2018 13:35:30 GMT+0100 (CET) system: Java version line: [java version "1.7.0_80"]
Thu Jan 25 2018 13:35:30 GMT+0100 (CET) system: Java version detected: [1.7.0_80]
Thu Jan 25 2018 13:35:30 GMT+0100 (CET) system: No supported Java found on your system! If you just installed, consider restarting your computer.`

And additionally:
`which java
/usr/lib/jvm/java-8-oracle/bin/java`

Edit: To be clear. I know that I have both installed, but `java` should point to 1.8.

**Comment by romansemko** [comment] 2018-01-25 20:37
hmm, by running "java" on your default command line environment, the default version seems to be 1.7... maybe the PATH variable is different in both cases so that java is found in different places depending on which comes first in the PATH

**Comment by 14Bkingrey** [comment] 2018-01-26 00:38
I had the same issue but solved it by downloading the Java JDK in addition to the Java JRE

**Comment by mailbox9494** [comment] 2018-01-28 13:38
I have same issue with mac-version 0.1.12. Java Error. Can u please help, I have the latest java version installed.

**Comment by 14Bkingrey** [comment] 2018-01-28 16:44
First Download the Java 8 JRE with this link: https://www.java.com/en/download/manual.jsp
Then Download the Java 8 JDK with this link: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Then download the newest bolero version and see if that works. It fixed the problem for me

**Comment by romansemko** [comment] 2018-01-29 07:04
@boxcee , can you confirm this solves the issue for you?

**Comment by boxcee** [comment] 2018-01-29 10:49
@romansemko, the above didn't work for me. However, I searched a bit through my setup and found that Java was used from `/etc/alternatives` and in there it still pointed to Java 7. Fixed the symbolic link and now the error message is gone. Now I still need to fix all the other links though :-)

**Comment by boxcee** [comment] 2018-01-29 11:04
Here is a good explanation of how to fix all symbolic links: https://superuser.com/questions/157743/batch-update-symbolic-links-recursively

**Comment by romansemko** [comment] 2018-02-01 06:18
Thanks for the input! I am closing this as it is not a bug in Bolero any more, but an OS-specific issue. We added a feature to the roadmap to automatically find all java installations and choose the best fitting one. Thanks for your time and input!

**Closed as completed by romansemko** 2018-02-01 06:18 UTC
Labels: bug, feedback needed
